version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  emote-generator:
    build:
      context: ./backend/emote-generator
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  analytics:
    build:
      context: ./backend/analytics
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    # TODO: REMOVE PORTS, FOR TESTING ONLY
    ports:
      - "3000:3000"

volumes:
  rabbitmq_data:

networks:
  backend: {}
